create extension if not exists pgcrypto;

-- =========================================================
-- STATIONS
-- =========================================================

create table if not exists public.stations (
    id text primary key,
    name text not null,
    device_key_hash text not null,

    latitude double precision,
    longitude double precision,
    address text,

    status text not null default 'offline'
        check (status in ('online', 'offline', 'maintenance')),

    firmware_version text,
    last_seen_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint stations_latitude_check
        check (
            latitude is null
            or latitude between -90 and 90
        ),

    constraint stations_longitude_check
        check (
            longitude is null
            or longitude between -180 and 180
        )
);

-- =========================================================
-- OBSERVATIONS
-- =========================================================

create table if not exists public.observations (
    id uuid primary key default gen_random_uuid(),

    station_id text not null
        references public.stations(id)
        on update cascade
        on delete restrict,

    idempotency_key text,

    captured_at timestamptz not null,
    received_at timestamptz not null default now(),

    image_path text not null,
    image_content_type text not null,
    image_width integer not null check (image_width > 0),
    image_height integer not null check (image_height > 0),

    temperature double precision,
    humidity double precision,

    firmware_version text,

    processing_status text not null default 'processing'
        check (
            processing_status in (
                'processing',
                'completed',
                'failed'
            )
        ),

    total_detected integer not null default 0
        check (total_detected >= 0),

    model_version text,
    inference_ms double precision,
    error_message text,

    created_at timestamptz not null default now()
);

create unique index if not exists
    observations_station_idempotency_unique
on public.observations (
    station_id,
    idempotency_key
)
where idempotency_key is not null;

create index if not exists
    observations_station_captured_idx
on public.observations (
    station_id,
    captured_at desc
);

create index if not exists
    observations_received_idx
on public.observations (
    received_at desc
);

create index if not exists
    observations_status_idx
on public.observations (
    processing_status
);

-- =========================================================
-- DETECTIONS
-- =========================================================

create table if not exists public.detections (
    id bigint generated by default as identity primary key,

    observation_id uuid not null
        references public.observations(id)
        on delete cascade,

    object_type text not null default 'mosquito',
    class_id integer not null check (class_id >= 0),

    species text not null,
    species_vi text,
    confidence double precision not null
        check (confidence between 0 and 1),

    detector_confidence double precision
        check (detector_confidence between 0 and 1),

    classification_confidence double precision
        check (classification_confidence between 0 and 1),

    classification_model_version text,
    review_required boolean not null default false,

    x1 double precision not null,
    y1 double precision not null,
    x2 double precision not null,
    y2 double precision not null,

    normalized_x1 double precision not null
        check (normalized_x1 between 0 and 1),

    normalized_y1 double precision not null
        check (normalized_y1 between 0 and 1),

    normalized_x2 double precision not null
        check (normalized_x2 between 0 and 1),

    normalized_y2 double precision not null
        check (normalized_y2 between 0 and 1),

    created_at timestamptz not null default now(),

    constraint detections_box_x_check check (x2 >= x1),
    constraint detections_box_y_check check (y2 >= y1)
);

create index if not exists
    detections_observation_idx
on public.detections (
    observation_id
);

create index if not exists
    detections_species_idx
on public.detections (
    species
);

-- Safe migration for databases created with the first MosGuardX schema.
alter table public.detections
    add column if not exists detector_confidence double precision
        check (detector_confidence between 0 and 1),
    add column if not exists classification_confidence double precision
        check (classification_confidence between 0 and 1),
    add column if not exists classification_model_version text,
    add column if not exists review_required boolean not null default false;

create index if not exists
    detections_review_required_idx
on public.detections (
    review_required,
    created_at desc
);

-- =========================================================
-- ALERTS
-- =========================================================

create table if not exists public.alerts (
    id uuid primary key default gen_random_uuid(),

    station_id text not null
        references public.stations(id)
        on update cascade
        on delete restrict,

    observation_id uuid
        references public.observations(id)
        on delete set null,

    level text not null
        check (
            level in (
                'low',
                'medium',
                'high',
                'critical'
            )
        ),

    title text not null,
    message text not null,

    status text not null default 'new'
        check (
            status in (
                'new',
                'acknowledged',
                'resolved'
            )
        ),

    created_at timestamptz not null default now(),
    acknowledged_at timestamptz,
    resolved_at timestamptz
);

create index if not exists
    alerts_station_created_idx
on public.alerts (
    station_id,
    created_at desc
);

create index if not exists
    alerts_status_idx
on public.alerts (
    status
);

-- =========================================================
-- UPDATED_AT TRIGGER
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists stations_set_updated_at
on public.stations;

create trigger stations_set_updated_at
before update on public.stations
for each row
execute function public.set_updated_at();

-- =========================================================
-- STORAGE BUCKETS
-- =========================================================

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'mosguardx-observations',
    'mosguardx-observations',
    false,
    10485760,
    array[
        'image/jpeg',
        'image/png',
        'image/webp'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'mosguardx-models',
    'mosguardx-models',
    false,
    104857600,
    array[
        'application/octet-stream',
        'application/x-pytorch'
    ]
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- =========================================================
-- SECURITY
-- Backend sử dụng service-role key.
-- Frontend không truy cập trực tiếp các bảng này.
-- =========================================================

alter table public.stations enable row level security;
alter table public.observations enable row level security;
alter table public.detections enable row level security;
alter table public.alerts enable row level security;
