"use client";

import { useState } from "react";
import { Bell, CheckCircle2 } from "lucide-react";
import { useLanguage } from "@/components/i18n/language-context";
import PageIntro from "@/components/ui/page-intro";
import { alerts as initialAlerts } from "@/data/mock-data";

const alertTitleTranslations: Record<string, string> = {
  "Mật độ muỗi tăng bất thường":
    "Abnormal increase in mosquito density",
  "Chỉ số nguy cơ vượt ngưỡng":
    "Risk index exceeded the threshold",
  "Thiết bị cần kiểm tra kết nối":
    "Device connection requires inspection",
};

const relativeTimeTranslations: Record<string, string> = {
  "8 phút trước": "8 minutes ago",
  "32 phút trước": "32 minutes ago",
  "1 giờ trước": "1 hour ago",
};

export default function AlertsPage() {
  const { language, tr } = useLanguage();
  const [alerts, setAlerts] = useState(initialAlerts);
  const [filter, setFilter] = useState("all");

  const visibleAlerts = alerts.filter(
    (alert) => filter === "all" || alert.status === filter,
  );

  function resolveAlert(id: string) {
    setAlerts((current) =>
      current.map((alert) =>
        alert.id === id ? { ...alert, status: "resolved" } : alert,
      ),
    );
  }

  return (
    <div>
      <PageIntro
        eyebrow={tr("TRUNG TÂM CẢNH BÁO", "ALERT CENTER")}
        title={tr("Quản lý và xử lý cảnh báo", "Alert management and resolution")}
        description={tr(
          "Xác nhận, theo dõi và đóng các cảnh báo phát sinh từ mạng lưới giám sát.",
          "Acknowledge, monitor, and close alerts generated by the monitoring network.",
        )}
      />

      <div className="mb-5 flex gap-2">
        {[
          ["all", tr("Tất cả", "All")],
          ["open", tr("Đang mở", "Open")],
          ["resolved", tr("Đã xử lý", "Resolved")],
        ].map(([value, label]) => (
          <button
            key={value}
            onClick={() => setFilter(value)}
            className={`rounded-xl px-4 py-2 text-xs font-bold ${
              filter === value
                ? "bg-emerald-600 text-white"
                : "border border-slate-200 bg-white text-slate-600"
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      <section className="space-y-4">
        {visibleAlerts.map((alert) => (
          <article
            key={alert.id}
            className="flex flex-col gap-4 rounded-2xl border border-[#dce8e2] bg-white p-5 md:flex-row md:items-center"
          >
            <span className="flex h-12 w-12 items-center justify-center rounded-xl bg-red-50 text-red-600">
              {alert.status === "resolved" ? (
                <CheckCircle2 />
              ) : (
                <Bell />
              )}
            </span>

            <div className="flex-1">
              <p className="text-xs font-bold text-emerald-700">{alert.id}</p>
              <h3 className="mt-1 font-bold text-[#16352a]">
                {language === "en"
                  ? alertTitleTranslations[alert.title] ?? alert.title
                  : alert.title}
              </h3>
              <p className="mt-1 text-sm text-slate-500">
                {language === "en"
                  ? alert.station.startsWith("Trạm ")
                    ? alert.station.replace(/^Trạm\s+/, "") + " Station"
                    : alert.station
                  : alert.station}{" "}
                ·{" "}
                {language === "en"
                  ? alert.location.replace(/,\s*Hà Nội$/, ", Hanoi")
                  : alert.location}{" "}
                ·{" "}
                {language === "en"
                  ? relativeTimeTranslations[alert.createdAt] ?? alert.createdAt
                  : alert.createdAt}
              </p>
            </div>

            <span
              className={`rounded-full px-3 py-1 text-xs font-bold ${
                alert.status === "resolved"
                  ? "bg-emerald-50 text-emerald-700"
                  : "bg-red-50 text-red-600"
              }`}
            >
              {alert.status === "resolved"
                ? tr("Đã xử lý", "Resolved")
                : tr("Đang mở", "Open")}
            </span>

            {alert.status !== "resolved" && (
              <button
                onClick={() => resolveAlert(alert.id)}
                className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white"
              >
                {tr("Đánh dấu đã xử lý", "Mark as resolved")}
              </button>
            )}
          </article>
        ))}

        {visibleAlerts.length === 0 && (
          <div className="rounded-2xl border border-[#dce8e2] bg-white p-12 text-center text-sm text-slate-500">
            {tr("Không có cảnh báo phù hợp.", "No matching alerts.")}
          </div>
        )}
      </section>
    </div>
  );
} 